// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: farmchain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateLocationData struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Timestamp        string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location         string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Temperature      string `protobuf:"bytes,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity         string `protobuf:"bytes,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	SoilMoisture     string `protobuf:"bytes,6,opt,name=soilMoisture,proto3" json:"soilMoisture,omitempty"`
	GrowthPercentage string `protobuf:"bytes,7,opt,name=growthPercentage,proto3" json:"growthPercentage,omitempty"`
	Crop             string `protobuf:"bytes,8,opt,name=crop,proto3" json:"crop,omitempty"`
}

func (m *MsgCreateLocationData) Reset()         { *m = MsgCreateLocationData{} }
func (m *MsgCreateLocationData) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLocationData) ProtoMessage()    {}
func (*MsgCreateLocationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{0}
}
func (m *MsgCreateLocationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLocationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLocationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLocationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLocationData.Merge(m, src)
}
func (m *MsgCreateLocationData) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLocationData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLocationData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLocationData proto.InternalMessageInfo

func (m *MsgCreateLocationData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateLocationData) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *MsgCreateLocationData) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *MsgCreateLocationData) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *MsgCreateLocationData) GetHumidity() string {
	if m != nil {
		return m.Humidity
	}
	return ""
}

func (m *MsgCreateLocationData) GetSoilMoisture() string {
	if m != nil {
		return m.SoilMoisture
	}
	return ""
}

func (m *MsgCreateLocationData) GetGrowthPercentage() string {
	if m != nil {
		return m.GrowthPercentage
	}
	return ""
}

func (m *MsgCreateLocationData) GetCrop() string {
	if m != nil {
		return m.Crop
	}
	return ""
}

type MsgCreateLocationDataResponse struct {
}

func (m *MsgCreateLocationDataResponse) Reset()         { *m = MsgCreateLocationDataResponse{} }
func (m *MsgCreateLocationDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLocationDataResponse) ProtoMessage()    {}
func (*MsgCreateLocationDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{1}
}
func (m *MsgCreateLocationDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLocationDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLocationDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLocationDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLocationDataResponse.Merge(m, src)
}
func (m *MsgCreateLocationDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLocationDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLocationDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLocationDataResponse proto.InternalMessageInfo

type MsgUpdateLocationData struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Timestamp        string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location         string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Temperature      string `protobuf:"bytes,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity         string `protobuf:"bytes,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	SoilMoisture     string `protobuf:"bytes,6,opt,name=soilMoisture,proto3" json:"soilMoisture,omitempty"`
	GrowthPercentage string `protobuf:"bytes,7,opt,name=growthPercentage,proto3" json:"growthPercentage,omitempty"`
	Crop             string `protobuf:"bytes,8,opt,name=crop,proto3" json:"crop,omitempty"`
}

func (m *MsgUpdateLocationData) Reset()         { *m = MsgUpdateLocationData{} }
func (m *MsgUpdateLocationData) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLocationData) ProtoMessage()    {}
func (*MsgUpdateLocationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{2}
}
func (m *MsgUpdateLocationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLocationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLocationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLocationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLocationData.Merge(m, src)
}
func (m *MsgUpdateLocationData) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLocationData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLocationData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLocationData proto.InternalMessageInfo

func (m *MsgUpdateLocationData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateLocationData) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *MsgUpdateLocationData) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *MsgUpdateLocationData) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *MsgUpdateLocationData) GetHumidity() string {
	if m != nil {
		return m.Humidity
	}
	return ""
}

func (m *MsgUpdateLocationData) GetSoilMoisture() string {
	if m != nil {
		return m.SoilMoisture
	}
	return ""
}

func (m *MsgUpdateLocationData) GetGrowthPercentage() string {
	if m != nil {
		return m.GrowthPercentage
	}
	return ""
}

func (m *MsgUpdateLocationData) GetCrop() string {
	if m != nil {
		return m.Crop
	}
	return ""
}

type MsgUpdateLocationDataResponse struct {
}

func (m *MsgUpdateLocationDataResponse) Reset()         { *m = MsgUpdateLocationDataResponse{} }
func (m *MsgUpdateLocationDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLocationDataResponse) ProtoMessage()    {}
func (*MsgUpdateLocationDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{3}
}
func (m *MsgUpdateLocationDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLocationDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLocationDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLocationDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLocationDataResponse.Merge(m, src)
}
func (m *MsgUpdateLocationDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLocationDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLocationDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLocationDataResponse proto.InternalMessageInfo

type MsgDeleteLocationData struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location  string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (m *MsgDeleteLocationData) Reset()         { *m = MsgDeleteLocationData{} }
func (m *MsgDeleteLocationData) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLocationData) ProtoMessage()    {}
func (*MsgDeleteLocationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{4}
}
func (m *MsgDeleteLocationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLocationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLocationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLocationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLocationData.Merge(m, src)
}
func (m *MsgDeleteLocationData) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLocationData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLocationData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLocationData proto.InternalMessageInfo

func (m *MsgDeleteLocationData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteLocationData) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *MsgDeleteLocationData) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type MsgDeleteLocationDataResponse struct {
}

func (m *MsgDeleteLocationDataResponse) Reset()         { *m = MsgDeleteLocationDataResponse{} }
func (m *MsgDeleteLocationDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLocationDataResponse) ProtoMessage()    {}
func (*MsgDeleteLocationDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8133440346f9cf58, []int{5}
}
func (m *MsgDeleteLocationDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLocationDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLocationDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLocationDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLocationDataResponse.Merge(m, src)
}
func (m *MsgDeleteLocationDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLocationDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLocationDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLocationDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateLocationData)(nil), "cosmonaut.farmchain.farmchain.MsgCreateLocationData")
	proto.RegisterType((*MsgCreateLocationDataResponse)(nil), "cosmonaut.farmchain.farmchain.MsgCreateLocationDataResponse")
	proto.RegisterType((*MsgUpdateLocationData)(nil), "cosmonaut.farmchain.farmchain.MsgUpdateLocationData")
	proto.RegisterType((*MsgUpdateLocationDataResponse)(nil), "cosmonaut.farmchain.farmchain.MsgUpdateLocationDataResponse")
	proto.RegisterType((*MsgDeleteLocationData)(nil), "cosmonaut.farmchain.farmchain.MsgDeleteLocationData")
	proto.RegisterType((*MsgDeleteLocationDataResponse)(nil), "cosmonaut.farmchain.farmchain.MsgDeleteLocationDataResponse")
}

func init() { proto.RegisterFile("farmchain/tx.proto", fileDescriptor_8133440346f9cf58) }

var fileDescriptor_8133440346f9cf58 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0xda, 0xda, 0x8f, 0xd5, 0x83, 0x2c, 0x08, 0x4b, 0xb1, 0xb1, 0xf4, 0x24, 0x1e, 0x52,
	0x51, 0x8f, 0x9e, 0xb4, 0x27, 0xb1, 0x20, 0x05, 0x2f, 0x5e, 0x64, 0x9b, 0xae, 0xc9, 0x62, 0x93,
	0x0d, 0xbb, 0x13, 0x6c, 0xff, 0x81, 0x17, 0xc1, 0x5f, 0xe1, 0x6f, 0xf1, 0xd8, 0xa3, 0x47, 0x69,
	0xff, 0x88, 0x74, 0xdb, 0x24, 0x95, 0xa4, 0x12, 0x04, 0x6f, 0xde, 0x66, 0xde, 0xcb, 0x63, 0x1e,
	0x6f, 0x26, 0x8b, 0xf0, 0x03, 0x95, 0x9e, 0xed, 0x52, 0xee, 0x77, 0x60, 0x6c, 0x05, 0x52, 0x80,
	0xc0, 0x4d, 0x5b, 0x28, 0x4f, 0xf8, 0x34, 0x04, 0x2b, 0x66, 0x93, 0xaa, 0xd1, 0x4c, 0x24, 0x23,
	0x61, 0x53, 0xe0, 0xc2, 0xbf, 0x1f, 0x52, 0xa0, 0x4b, 0x75, 0xfb, 0xa5, 0x88, 0xf6, 0x7a, 0xca,
	0xb9, 0x94, 0x8c, 0x02, 0xbb, 0x5e, 0x7d, 0xd0, 0xa5, 0x40, 0x31, 0x41, 0x55, 0x7b, 0x81, 0x0a,
	0x49, 0x8c, 0x96, 0x71, 0x58, 0xef, 0x47, 0x2d, 0xde, 0x47, 0x75, 0xe0, 0x1e, 0x53, 0x40, 0xbd,
	0x80, 0x14, 0x35, 0x97, 0x00, 0xb8, 0x81, 0x6a, 0xd1, 0x20, 0x52, 0xd2, 0x64, 0xdc, 0xe3, 0x16,
	0xda, 0x06, 0xe6, 0x05, 0x4c, 0x52, 0x08, 0x25, 0x23, 0x65, 0x4d, 0xaf, 0x43, 0x0b, 0xb5, 0x1b,
	0x7a, 0x7c, 0xc8, 0x61, 0x42, 0xb6, 0x96, 0xea, 0xa8, 0xc7, 0x6d, 0xb4, 0xa3, 0x04, 0x1f, 0xf5,
	0x04, 0x57, 0x5a, 0x5e, 0xd1, 0xfc, 0x37, 0x0c, 0x1f, 0xa1, 0x5d, 0x47, 0x8a, 0x27, 0x70, 0x6f,
	0x98, 0xb4, 0x99, 0x0f, 0xd4, 0x61, 0xa4, 0xaa, 0xbf, 0x4b, 0xe1, 0x18, 0xa3, 0xb2, 0x2d, 0x45,
	0x40, 0x6a, 0x9a, 0xd7, 0x75, 0xfb, 0x00, 0x35, 0x33, 0xe3, 0xe8, 0x33, 0x15, 0x08, 0x5f, 0xb1,
	0x28, 0xb0, 0xdb, 0x60, 0xf8, 0x1f, 0x58, 0x12, 0x58, 0x3a, 0x8e, 0x38, 0xb0, 0x47, 0x9d, 0x57,
	0x97, 0x8d, 0xd8, 0xdf, 0xe7, 0xb5, 0x72, 0x93, 0x1e, 0x16, 0xb9, 0x39, 0x79, 0x2b, 0xa1, 0x52,
	0x4f, 0x39, 0xf8, 0xd9, 0x40, 0x38, 0xe3, 0xe8, 0xcf, 0xac, 0x1f, 0xff, 0x26, 0x2b, 0xf3, 0x36,
	0x1a, 0xe7, 0xbf, 0x51, 0x45, 0x96, 0xb4, 0x95, 0x8c, 0x73, 0xca, 0x61, 0x25, 0xad, 0xca, 0x63,
	0x65, 0xf3, 0xae, 0xb4, 0x95, 0x8c, 0x4d, 0xe5, 0xb0, 0x92, 0x56, 0xe5, 0xb1, 0xb2, 0x79, 0x51,
	0x17, 0x57, 0xef, 0x33, 0xd3, 0x98, 0xce, 0x4c, 0xe3, 0x73, 0x66, 0x1a, 0xaf, 0x73, 0xb3, 0x30,
	0x9d, 0x9b, 0x85, 0x8f, 0xb9, 0x59, 0xb8, 0x3b, 0x76, 0x38, 0xb8, 0xe1, 0xc0, 0xb2, 0x85, 0xd7,
	0x89, 0x27, 0x74, 0x92, 0x67, 0x6e, 0xbc, 0x56, 0xc3, 0x24, 0x60, 0x6a, 0x50, 0xd1, 0x6f, 0xdd,
	0xe9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x22, 0x8c, 0xcb, 0x3f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateLocationData(ctx context.Context, in *MsgCreateLocationData, opts ...grpc.CallOption) (*MsgCreateLocationDataResponse, error)
	UpdateLocationData(ctx context.Context, in *MsgUpdateLocationData, opts ...grpc.CallOption) (*MsgUpdateLocationDataResponse, error)
	DeleteLocationData(ctx context.Context, in *MsgDeleteLocationData, opts ...grpc.CallOption) (*MsgDeleteLocationDataResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateLocationData(ctx context.Context, in *MsgCreateLocationData, opts ...grpc.CallOption) (*MsgCreateLocationDataResponse, error) {
	out := new(MsgCreateLocationDataResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.farmchain.farmchain.Msg/CreateLocationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLocationData(ctx context.Context, in *MsgUpdateLocationData, opts ...grpc.CallOption) (*MsgUpdateLocationDataResponse, error) {
	out := new(MsgUpdateLocationDataResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.farmchain.farmchain.Msg/UpdateLocationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteLocationData(ctx context.Context, in *MsgDeleteLocationData, opts ...grpc.CallOption) (*MsgDeleteLocationDataResponse, error) {
	out := new(MsgDeleteLocationDataResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.farmchain.farmchain.Msg/DeleteLocationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateLocationData(context.Context, *MsgCreateLocationData) (*MsgCreateLocationDataResponse, error)
	UpdateLocationData(context.Context, *MsgUpdateLocationData) (*MsgUpdateLocationDataResponse, error)
	DeleteLocationData(context.Context, *MsgDeleteLocationData) (*MsgDeleteLocationDataResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateLocationData(ctx context.Context, req *MsgCreateLocationData) (*MsgCreateLocationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocationData not implemented")
}
func (*UnimplementedMsgServer) UpdateLocationData(ctx context.Context, req *MsgUpdateLocationData) (*MsgUpdateLocationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocationData not implemented")
}
func (*UnimplementedMsgServer) DeleteLocationData(ctx context.Context, req *MsgDeleteLocationData) (*MsgDeleteLocationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLocationData not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateLocationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLocationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLocationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.farmchain.farmchain.Msg/CreateLocationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLocationData(ctx, req.(*MsgCreateLocationData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLocationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLocationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLocationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.farmchain.farmchain.Msg/UpdateLocationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLocationData(ctx, req.(*MsgUpdateLocationData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteLocationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteLocationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteLocationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.farmchain.farmchain.Msg/DeleteLocationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteLocationData(ctx, req.(*MsgDeleteLocationData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.farmchain.farmchain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLocationData",
			Handler:    _Msg_CreateLocationData_Handler,
		},
		{
			MethodName: "UpdateLocationData",
			Handler:    _Msg_UpdateLocationData_Handler,
		},
		{
			MethodName: "DeleteLocationData",
			Handler:    _Msg_DeleteLocationData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "farmchain/tx.proto",
}

func (m *MsgCreateLocationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLocationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLocationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Crop) > 0 {
		i -= len(m.Crop)
		copy(dAtA[i:], m.Crop)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Crop)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.GrowthPercentage) > 0 {
		i -= len(m.GrowthPercentage)
		copy(dAtA[i:], m.GrowthPercentage)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GrowthPercentage)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SoilMoisture) > 0 {
		i -= len(m.SoilMoisture)
		copy(dAtA[i:], m.SoilMoisture)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SoilMoisture)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Humidity) > 0 {
		i -= len(m.Humidity)
		copy(dAtA[i:], m.Humidity)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Humidity)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Temperature) > 0 {
		i -= len(m.Temperature)
		copy(dAtA[i:], m.Temperature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Temperature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLocationDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLocationDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLocationDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLocationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLocationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLocationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Crop) > 0 {
		i -= len(m.Crop)
		copy(dAtA[i:], m.Crop)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Crop)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.GrowthPercentage) > 0 {
		i -= len(m.GrowthPercentage)
		copy(dAtA[i:], m.GrowthPercentage)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GrowthPercentage)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SoilMoisture) > 0 {
		i -= len(m.SoilMoisture)
		copy(dAtA[i:], m.SoilMoisture)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SoilMoisture)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Humidity) > 0 {
		i -= len(m.Humidity)
		copy(dAtA[i:], m.Humidity)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Humidity)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Temperature) > 0 {
		i -= len(m.Temperature)
		copy(dAtA[i:], m.Temperature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Temperature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLocationDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLocationDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLocationDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLocationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLocationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLocationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLocationDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLocationDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLocationDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateLocationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Temperature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Humidity)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SoilMoisture)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GrowthPercentage)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Crop)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLocationDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateLocationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Temperature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Humidity)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SoilMoisture)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GrowthPercentage)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Crop)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateLocationDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteLocationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteLocationDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateLocationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLocationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLocationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Temperature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Temperature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Humidity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Humidity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoilMoisture", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SoilMoisture = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrowthPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrowthPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crop", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Crop = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLocationDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLocationDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLocationDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLocationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLocationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLocationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Temperature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Temperature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Humidity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Humidity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoilMoisture", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SoilMoisture = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrowthPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrowthPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crop", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Crop = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLocationDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLocationDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLocationDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLocationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLocationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLocationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLocationDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLocationDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLocationDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
